project:
  type: website
  pre-render:
    - ./pre-render.py
  post-render:
    - ./post-render.py
  render:
    - "index.qmd"
    - "RESUME.qmd"

website:
  title: "Mi Página Personal"
  navbar:
    left:
      - href: index.qmd
        text: "Inicio"
      - href: RESUME.qmd
        text: "CV"
  page-footer:
    border: true
    background: dark
    center: 
      - text: "<b>Download PDF</b>"
        href: /index.pdf

format-links: false
format:
  html:
    theme: minty
    css: styles.css
    link-external-newwindow: true
    canonical-url: true
  pdf: default

resources:
  - CNAME

