# Alberto Cascajo
Doctor of Computer Science and Technology
| [acascajo@inf.uc3m.es](mailto:acascajo@inf.uc3m.es)
| [+34 916246260](tel:+34916246260)
| [LinkedIn.com](https://www.linkedin.com/in/albertocascajosofteng/)


## Work Experience

### Post-Doctoral Researcher, University Carlos III of Madrid
*Feb 2022 - Present*

- Computational epidemiology 
- High-Performance Computing
- Dynamic Resource Management features on HPC platforms
- Monitoring large-scale platform
- Developing railway simulators in cooperation with a specialized company
- Edge computing

### Associate Professor, University Carlos III of Madrid
*July 2016 - present*

- Computer Architecture: The main objective of this course is to know the basic concepts about the architecture of a computer and its impact on the performance of applications and computer systems. In its practical part, this knowledge should be applied using lock-free programming (lower-level parallelism). The language used is C/C ++.

- Operating Systems: The main objective of this subject is to know the function of the operating system as an extended machine, the services it oﬀers to the rest of the system, and its main components and entities (processes, memory, files, etc.), the concepts of concurrency, and the relationships of the operating system with the rest of the computer software and hardware. We focus on understanding the functionality that the operating system includes and that the applications can use. In addition, we teach how task schedulers work, how programs interact and communicate with each other, and how the application threads work in concurrent programming. The language used is C.

- Computer Structure: The main objective of this subject is to understand basic concepts about the organization and structure of a computer, such as data representation, basic arithmetic, execution of instructions, assembly programming, main memory, cache and virtual memory, and I/O systems. The practical environment in this subject includes the RISC-V architecture for assembly programming and microprogramming (implementing the micro-code of the instructions).

### Software developer, University Carlos III of Madrid
*May 2013 - Aug 2017*

- Software developer in diﬀerent languages for different applications (C/C++, C#, Python, Shelscripts).
- Development and maintenance of simulation software for companies (C#).


## Education

### Doctorate in Computer Science and Technology 
*University Carlos III of Madrid*  
*Dec 2021 - Cum Laude*

Thesis title: New cross-layer techniques for multi-criteria scheduling in large-scale systems

### Master in Computer Science and Technology
*University Carlos III of Madrid*  
*Sep 2017 - Excellent*

Thesis title (es): Optimización de herramientas de simulación científica: HidroGeoSphere.
Thesis title (en): Optimization of scientific simulation tools: HidroGeoSphere.

### Bachelor degree in Computer Science
*University Carlos III of Madrid*  
*Sep 2016 - 8/10*

Thesis title (es): Optimización de aplicaciones de cálculo estructural y generación automática de informes.
Thesis title (en): Optimization of structural calculation applications and automatic report generation.


## Projects

### MADE: Multiple Access to eDElivery
*Jan 2017 - Dec 2018*

Participation: Member of the working group

### eID@Cloud: Integrating de eIdentification in European cloud Platform according to the EIDAs Regulation
*May 2017 - Sep 2018*

Participation: Member of the working group

### ADMIRE: Adaptive multi-tier intelligent data manager for Exascale
*Apr 2021 - Mar 2024*

Participation: Member of the working group

### Servicio para el desarrollo de una herramienta de predicción de escenarios epidemiológicos y de vacunación frente a COVID-19
*Aug 2021 - Nov 2021*

Participation: Member of the working group

### eID4Spain: Connecting Regional and Local Administrations to Spanish eIDAS Node
*Sep 2018 - Feb 2020*

Participation: Member of the working group

### SIRTE: Simulación de la Interacción y Replanteo de Trazados Electrificados y Pórticos y Agujas
*Feb 2010 - Dec 2013*

Participation: Internship

### Estudio y realización de programas de cálculo de pórticos rígidos de catenaria (CALPOR) y de Sistemas de simulación de montaje de agujas aéreas de línea aérea de contacto (SIA)
*Feb 2007 - Jan 2011*

Participation: Internship

### Mantenimiento del programa: Sistema de análisis y cálculo de suministro de energía
*Apr 2021 - Dec 2021*

Participation: Member of the working group

### Nuevos métodos en High-end y Edge Computing para la computación intensiva en datos
*Jun 2020 - Feb 2024*

Participation: Member of the working group

### Hacia la unificación de paradigmas HPC y Big Data
*Dec 2016 - May 2020*

Participation: Member of the working group

### Projects of the Spanish Supercomputing Network (Red Española de Supercomputación - RES)
*Jul 2021 - Nov 2023*

Participation: Member of the working group

- BCV-2021-2-0011 - Evaluation of COVID19 mitigation and vaccination strategies.
- BCV-2021-3-0007 - Evaluation of COVID19 mitigation and vaccination strategies.
- BCV-2022-1-0005 - Analysis tool for COVID-19 vaccination scenarios.
- BCV-2022-1-0004 - Multi-source and multi-method prediction to support COVID-19 policy decision making.
- BCV-2022-2-0010 - Analysis tool for COVID-19 vaccination scenarios. 
- BCV-2022-3-0004 - Modelling COVID-19 propagation scenarios for health authority decision making.
- BCV-2023-1-0005 - Modelling COVID-19 propagation scenarios for health authority decision making.
- BCV-2023-2-0012 - Fine-grained COVID-19 forecasting.
- BCV-2023-3-0004 Fine-grained COVID-19 forecasting.

### Technical Reports elaboration – European Centre for Disease Prevention and Control (ECDC)
*Dec 2021 - Jan 2022*

Participation: Member of the working group

- European Covid-19 Forecast Hub. Duración: del 1/12/2021 a la actualidad.
- European Covid-19 Scenario Hub. Duración: del 1/1/2022 a la actualidad.

### Nuevas técnicas escalables de E/S para cargas de trabajo híbridas de HPC e intensivas en datos. 
*Sep 2023 - Aug 2026*

Participation: Member of the working group

### Monitorización y Evaluación en Tiempo Real de Infraestructuras Cloud y HPC mediante IA - METRIC-AI
*Jan 2025 - Dec 2025*

Participation: IP - Main researcher

## Languages

- English: Fluent
- Spanish: Native
- German: Beginner

## Skills

- Data Analysis: C/C++, Python, SQL, scripting
- Visualization Tools: Grafana, Kibana
- Machine Learning: Scikit-learn, TensorFlow
- AI: neural networks
- High-Performance Computing: remote work in clusters, cluster configuration and maintenance

## Certifications

- Mobile application developement (40h) Certificate - 2017
- Personal productivity course in the Digital Era - 2017
- Cloud computing course (40h) - 2017
- Improving your English-Speaking Skills (B2/C1) Certificate - 2021
  
## Interests

- Technology
- Sports (soccer, tennis, padel)
- Cars and motorbikes
- Photography
